### PR TITLE
Fixing bug #2!Accessing answer easier!

### PR DESCRIPTION
**Pull request by alirezadigi**
Resolving https://github.com/alirezaahani/endless_questions/issues/2
The user can acsess the answer by typing hint!

### CODE REVIEW

**Comment by alirezadigi** [comment]
Hi Dear @alirezaahani !
I have sent you a PR! Please ask me if you have any questions!Thanks!

**Comment by alirezaahani** [comment]
Thank you 🌹
At the moment I can not review your code because github in mobile phone is not very nice.

**Comment by alirezaahani** [comment]
Looks like the output is very clean now , Thank you

**Comment by alirezadigi** [comment]
You'r Welcome!Thanks!

**Pull request merged**
